---
- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  become: true
  listen: restart apache

- name: Install Django
  ansible.builtin.command:
    chdir: /opt/{{ django_project_name }}/site
    cmd: /opt/{{ django_project_name }}/venv/bin/pip install -r requirements.txt
  register: result
  changed_when: "'Successfully installed' in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated

- name: Run migrations
  ansible.builtin.command:
    chdir: /opt/{{ django_project_name }}/site
    cmd: /opt/{{ django_project_name }}/venv/bin/python manage.py migrate
  register: result
  changed_when: "'No migrations to apply' not in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated

- name: Create a superuser
  ansible.builtin.command:
    chdir: /opt/{{ django_project_name }}/site
    cmd: /opt/{{ django_project_name }}/venv/bin/python manage.py ensure_super_user
  environment:
    DJANGO_SUPERUSER_USERNAME: "{{ home_site_admin_username }}"
    DJANGO_SUPERUSER_EMAIL: "{{ home_site_admin_email }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ home_site_admin_password }}"
  changed_when: "'Superuser created successfully' in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated

- name: Collect static files
  ansible.builtin.command:
    chdir: /opt/{{ django_project_name }}/site
    cmd: /opt/{{ django_project_name }}/venv/bin/python manage.py collectstatic --noinput
  register: result
  changed_when: "'0 static files copied to' not in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated
