---
- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  become: true
  listen: restart apache

- name: Run migrations
  ansible.builtin.command:
    cmd: /opt/{{ django_project_name }}/venv/bin/python manage.py migrate
  register: result
  changed_when: "'No migrations to apply' not in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated

- name: Collect static files
  ansible.builtin.command:
    cmd: /opt/{{ django_project_name }}/venv/bin/python manage.py collectstatic --noinput
  register: result
  changed_when: "'0 static files copied to' not in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated

- name: Install Django
  ansible.builtin.command:
    cmd: /opt/{{ django_project_name }}/venv/bin/pip install -r requirements.txt
  register: result
  changed_when: "'Successfully installed' in result.stdout"
  become_user: www-data
  become: true
  listen: git repository updated
